Fixes not being able to put makers on monsters
cyruzzo/AboveVTT pull request #464
Opened 2022-05-04 03:47 UTC by Azmoria

Fixes: #463

2022-05-04 20:52 UTC, vlaminck approved these changes

2022-05-05 07:27 UTC, bain2236 commented
I dropped the ball on this one. But this totally fixes it

2022-05-07 12:25 UTC, vlaminck requested changes
`pop` doesn't work like that. I always pops no matter what the value is. I fixed this in your token context menu rebuild branch so this PR probably isn't needed any more, but this is how I fixed it


    if (this.options.inspiration){
        if (!this.options.custom_conditions.includes("Inspiration")){
            this.options.custom_conditions.push("Inspiration")
        }
    }
    else {
        array_remove_index_by_value(this.options.custom_conditions, "Inspiration");
    }

2022-05-07 17:16 UTC, Azmoria commented
> `pop` doesn't work like that. I always pops no matter what the value is. I fixed this in your token context menu rebuild branch so this PR probably isn't needed any more, but this is how I fixed it
> 
> ```
> if (this.options.inspiration){
>     if (!this.options.custom_conditions.includes("Inspiration")){
>         this.options.custom_conditions.push("Inspiration")
>     }
> }
> else {
>     array_remove_index_by_value(this.options.custom_conditions, "Inspiration");
> }
> ```

Yeh that makes sense I had just wrapped what was there to check if inspiration was there. This seemed to fix the issue so I left it. Closing this since your fix is in the other one

2022-05-07 17:16 UTC, closed without merging